FROM registry.access.redhat.com/ubi9/ubi:latest

USER root

RUN yum -y update && \
    yum -y install file binutils pam-devel numactl-devel libaio-devel git gcc && \
    && dnf clean all \
  	&& rm -rf /var/cache/yum

# OpenShift requires images to run as non-root by default
USER 1001
ENTRYPOINT ["/bin/bash"]
